spring:
  application:
    name: backend-cart-app
  datasource:
    url: jdbc:mysql://localhost/db_cart_app
    username: root
    password: FerMar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    time-zone: America/Bogota
    locale: es_CO
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9000
  servlet:
    context-path: /cart-app/v1