insert into products (name, description, price) values ('Samsung 4k', 'Smart tv de 120 cm', 10000);
insert into products (name, description, price) values ('Sony Mx3', 'Camara profesional', 7500);
insert into products (name, description, price) values ('Xbox series s', 'consola de video juego 1tb', 3000);
insert into products (name, description, price) values ('Nvidia RTX4090', 'Tarjeta de video grafica', 2300);
insert into products (name, description, price) values ('Samsung S23 Ultra', 'Smarphone samsung IA', 4000);
INSERT INTO products (name, description, price) VALUES ('Teclado Logitech', 'Inalámbrico', 1000);
INSERT INTO products (name, description, price) VALUES ('Mouse Logitech', 'Ergonómico y óptico', 500);
INSERT INTO products (name, description, price) VALUES ('Monitor Samsung', '24 pulgadas Full HD', 4500);
INSERT INTO products (name, description, price) VALUES ('Laptop Dell', 'Intel Core i7, 16GB RAM, 512GB SSD', 35000);
INSERT INTO products (name, description, price) VALUES ('Disco Duro Externo Seagate', '2TB, USB 3.0', 2500);
INSERT INTO products (name, description, price) VALUES ('Auriculares Sony', 'Cancelación de ruido, Bluetooth', 3000);
INSERT INTO products (name, description, price) VALUES ('Impresora HP', 'Multifuncional, Wi-Fi', 4000);
INSERT INTO products (name, description, price) VALUES ('Tablet Apple iPad', '10.2 pulgadas, 128GB', 8000);
INSERT INTO products (name, description, price) VALUES ('Smartphone Samsung Galaxy', '6.5 pulgadas, 128GB', 15000);
INSERT INTO products (name, description, price) VALUES ('Router TP-Link', 'Dual Band, 1200Mbps', 1200);
INSERT INTO products (name, description, price) VALUES ('Cámara Canon', 'DSLR, 24.1 MP', 25000);
INSERT INTO products (name, description, price) VALUES ('Smartwatch Apple', 'Serie 6, GPS', 12000);
INSERT INTO products (name, description, price) VALUES ('Parlante JBL', 'Portátil, Bluetooth', 1800);
INSERT INTO products (name, description, price) VALUES ('Silla Gamer', 'Ergonómica, ajustable', 4500);
INSERT INTO products (name, description, price) VALUES ('Teclado Mecánico Razer', 'Retroiluminado, switches verdes', 3200);
INSERT INTO products (name, description, price) VALUES ('Tarjeta Gráfica Nvidia', 'RTX 3080, 10GB GDDR6X', 70000);
INSERT INTO products (name, description, price) VALUES ('Memoria USB Kingston', '64GB, USB 3.0', 600);
INSERT INTO products (name, description, price) VALUES ('Fuente de Poder Corsair', '750W, 80 Plus Gold', 3500);
INSERT INTO products (name, description, price) VALUES ('Procesador AMD Ryzen', 'Ryzen 9 5900X, 12 núcleos', 25000);
INSERT INTO products (name, description, price) VALUES ('Placa Base ASUS', 'Z590, Intel, ATX', 12000);
